<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BUTTON_LOGIN' => 'Войти',
    'BUTTON_PASSWORD_CHANGE' => 'Изменить пароль',
    'BUTTON_SIGNUP' => 'Зарегистрироваться',
    'CREATED' => 'Создан',
    'CURRENT_PASSWORD' => 'Текущий пароль',
    'EMAIL' => 'Email',
    'EMAIL_CONFIRMATION_FOR' => 'Подтверждение email: ',
    'EMAIL_CONFIRM_TOKEN_CANNOT_BE_BLANK' => 'Не найден токен для подтверждения регистрации',
    'ERROR_EMAIL_EXISTS' => 'Этот Email уже используется.',
    'ERROR_PROFILE_BLOCKED' => 'Ваш аккаунт заблокирован.',
    'ERROR_PROFILE_NOT_CONFIRMED' => 'Ваш аккаунт не подтвержден.',
    'ERROR_USER_NOT_FOUND_BY_EMAIL' => 'Пользователь с таким адресом не найден.',
    'ERROR_WRONG_CURRENT_PASSWORD' => 'Неверный текущий пароль.',
    'ERROR_WRONG_USERNAME_OR_PASSWORD' => 'Неверное имя пользователя или пароль.',
    'FLASH_EMAIL_CONFIRM_ERROR' => 'Ошибка подтверждения Email.',
    'FLASH_EMAIL_CONFIRM_REQUEST' => 'Подтвердите ваш электронный адрес.',
    'FLASH_EMAIL_CONFIRM_SUCCESS' => 'Спасибо! Ваш Email успешно подтверждён.',
    'FLASH_PASSWORD_RESET_ERROR' => 'Извините. У нас возникли проблемы с отправкой.',
    'FLASH_PASSWORD_RESET_REQUEST' => 'Спасибо! На ваш Email было отправлено письмо со ссылкой на восстановление пароля.',
    'FLASH_PASSWORD_RESET_SUCCESS' => 'Спасибо! Пароль успешно изменён.',
    'FOLLOW_TO_CONFIRM_EMAIL' => 'Для подтверждения адреса пройдите по ссылке:',
    'FOLLOW_TO_RESET_PASSWORD' => 'Для смены пароля пройдите по ссылке:',
    'IGNORE_IF_DO_NOT_REGISTER' => 'Если Вы не регистрировались на нашем сайте, то просто удалите это письмо.',
    'LINK_PASSWORD_RESET' => 'Восстановить пароль',
    'NEW_PASSWORD' => 'Новый пароль',
    'NEW_PASSWORD:' => 'Новый пароль:',
    'PASSWORD' => 'Пароль',
    'PASSWORD:' => 'Пароль:',
    'PASSWORD_RESET_FOR' => 'Сброс пароля: ',
    'PASSWORD_RESET_TOKEN_CANNOT_BE_BLANK' => 'Не найден токен для подтверждения сброса пароля',
    'PLEASE_FILL_FOR_LOGIN' => 'Для входа на сайт введите данные своей учётной записи:',
    'PLEASE_FILL_FOR_RESET' => 'Введите новый пароль:',
    'PLEASE_FILL_FOR_RESET_REQUEST' => 'Введите свой Email и мы пришлём Вам инструкцию по восстановлению:',
    'PLEASE_FILL_FOR_SIGNUP' => 'Для регистрации заполните следующие поля:',
    'REMEMBER_ME' => 'Запомнить меня',
    'REPEAT_PASSWORD' => 'Повторите пароль',
    'STATUS' => 'Статус',
    'STATUS_ACTIVED' => 'Активен',
    'STATUS_BLOCKED' => 'Заблокирован',
    'STATUS_WAITED' => 'Ожидает подтверждения',
    'TITLE_LOGIN' => 'Вход',
    'TITLE_PASSWORD_CHANGE' => 'Смена пароля',
    'TITLE_PASSWORD_RESET' => 'Восстановление пароля',
    'TITLE_PROFILE' => 'Профиль',
    'TITLE_REQUEST_PASSWORD_RESET' => 'Сброс пароля',
    'TITLE_SIGNUP' => 'Регистрация',
    'USERNAME' => 'ФИО',
    'USERNAME:' => 'ФИО:',
    'USER_NOT_FOUND' => 'Пользователь не найден',
    'WRONG_EMAIL_CONFIRM_TOKEN' => 'Неверный токен',
    'WRONG_PASSWORD_RESET_TOKEN' => 'Неверный токен',
];
