<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'BUTTON_CREATE' => 'Добавить',
    'BUTTON_DELETE' => 'Удалить',
    'BUTTON_RESET' => 'Сбросить',
    'BUTTON_SAVE' => 'Сохранить',
    'BUTTON_SEARCH' => 'Искать',
    'BUTTON_SEND' => 'Отправить',
    'BUTTON_UPDATE' => 'Редактировать',
    'ERROR!' => 'Ошибка!',
    'HELLO' => 'Здравствуйте',
    'ID' => 'ID',
    'More than 6 symbols' => '',
    'NAV_ADMIN' => 'Админка',
    'NAV_HOME' => 'Главная',
    'NAV_LOGIN' => 'Войти',
    'NAV_LOGOUT' => 'Выйти',
    'NAV_PROFILE' => 'Профиль',
    'NAV_SIGNUP' => 'Регистрация',
    'NAV_USERS' => 'Пользователи',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'SUCCESS!' => 'Успешно!',
    'TITLE_CREATE' => 'Добавление',
    'TITLE_UPDATE' => 'Редактирование',
    'TITLE_UPDATE: ' => 'Редактирование: ',
    'The above error occurred while the Web server was processing your request.' => '',
];
