<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTENT' => 'Содержимое',
    'CREATED' => 'Создано',
    'DATE_FROM' => 'С',
    'DATE_TO' => 'По',
    'EXIST' => 'Есть',
    'FILES' => 'Файлы',
    'FROM' => 'Отправитель',
    'HEADERS' => 'Заголовки ',
    'HTML' => 'Html',
    'NO' => 'Нет',
    'RAW' => 'Исходник',
    'REQUESTED_FILE_NOT_FOUND' => 'Файл не найден',
    'SAVE_MAIL' => 'Сохранить',
    'SUBJECT' => 'Тема',
    'TEXT' => 'Текст',
    'TITLE_MAILS' => 'Письма',
    'TO' => 'Получатель',
    'TYPE' => 'Тип',
    'TYPE_IN' => 'Входящее',
    'TYPE_OUT' => 'Исходящее',
    'XML' => 'XML',
];
