<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BUTTON_LOGIN' => '',
    'BUTTON_PASSWORD_CHANGE' => '',
    'BUTTON_SIGNUP' => '',
    'CREATED' => '',
    'CURRENT_PASSWORD' => '',
    'EMAIL' => '',
    'EMAIL_CONFIRMATION_FOR' => '',
    'EMAIL_CONFIRM_TOKEN_CANNOT_BE_BLANK' => '',
    'ERROR_EMAIL_EXISTS' => '',
    'ERROR_PROFILE_BLOCKED' => '',
    'ERROR_PROFILE_NOT_CONFIRMED' => '',
    'ERROR_USER_NOT_FOUND_BY_EMAIL' => '',
    'ERROR_WRONG_CURRENT_PASSWORD' => '',
    'ERROR_WRONG_USERNAME_OR_PASSWORD' => '',
    'FLASH_EMAIL_CONFIRM_ERROR' => '',
    'FLASH_EMAIL_CONFIRM_REQUEST' => '',
    'FLASH_EMAIL_CONFIRM_SUCCESS' => '',
    'FLASH_PASSWORD_RESET_ERROR' => '',
    'FLASH_PASSWORD_RESET_REQUEST' => '',
    'FLASH_PASSWORD_RESET_SUCCESS' => '',
    'FOLLOW_TO_CONFIRM_EMAIL' => '',
    'FOLLOW_TO_RESET_PASSWORD' => '',
    'IGNORE_IF_DO_NOT_REGISTER' => '',
    'LINK_PASSWORD_RESET' => '',
    'NEW_PASSWORD' => '',
    'NEW_PASSWORD:' => '',
    'PASSWORD' => '',
    'PASSWORD:' => '',
    'PASSWORD_RESET_FOR' => '',
    'PASSWORD_RESET_TOKEN_CANNOT_BE_BLANK' => '',
    'PLEASE_FILL_FOR_LOGIN' => '',
    'PLEASE_FILL_FOR_RESET' => '',
    'PLEASE_FILL_FOR_RESET_REQUEST' => '',
    'PLEASE_FILL_FOR_SIGNUP' => '',
    'REMEMBER_ME' => '',
    'REPEAT_PASSWORD' => '',
    'STATUS' => '',
    'STATUS_ACTIVED' => '',
    'STATUS_BLOCKED' => '',
    'STATUS_WAITED' => '',
    'TITLE_LOGIN' => '',
    'TITLE_PASSWORD_CHANGE' => '',
    'TITLE_PASSWORD_RESET' => '',
    'TITLE_PROFILE' => '',
    'TITLE_REQUEST_PASSWORD_RESET' => '',
    'TITLE_SIGNUP' => '',
    'USERNAME' => '',
    'USERNAME:' => '',
    'USER_NOT_FOUND' => '',
    'WRONG_EMAIL_CONFIRM_TOKEN' => '',
    'WRONG_PASSWORD_RESET_TOKEN' => '',
];
