<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'BUTTON_CREATE' => '',
    'BUTTON_DELETE' => '',
    'BUTTON_RESET' => '',
    'BUTTON_SAVE' => '',
    'BUTTON_SEARCH' => '',
    'BUTTON_SEND' => '',
    'BUTTON_UPDATE' => '',
    'ERROR!' => '',
    'HELLO' => '',
    'ID' => '',
    'More than 6 symbols' => '',
    'NAV_ADMIN' => '',
    'NAV_HOME' => '',
    'NAV_LOGIN' => '',
    'NAV_LOGOUT' => '',
    'NAV_PROFILE' => '',
    'NAV_SIGNUP' => '',
    'NAV_USERS' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'SUCCESS!' => '',
    'TITLE_CREATE' => '',
    'TITLE_UPDATE' => '',
    'TITLE_UPDATE: ' => '',
    'The above error occurred while the Web server was processing your request.' => '',
];
